### PR TITLE
refactor!: remove nvim-treesitter dependency

### PR DESCRIPTION
**Pull request by amaanq**
Nvim-treesitter's 1.0 rewrite will remove all utilities/functionality it provides since vim.treesitter pretty much covers it all now,  you can read more in the *main* branch's readme (default is master)

### CODE REVIEW

**Comment by wookayin** [comment]
Great PR. One note is that the `vim.treesitter.*` APIs require neovim 0.9 or higher, so this would have an impact on the minimum supported neovim version (so it's technically a breaking change towards v4.0).

**Comment by amaanq** [comment]
Yeah hence why I marked it a breaking change :) I completely forgot I wrote that old PR 3 months ago...

**Comment by rcarriga** [comment]
Thanks for the PR! :smile: The failing test is fixed in master so merging

**Comment by wookayin** [comment]
This PR seems incomplete - we'd need to take care of nvim requirement?

**Pull request merged**
