### PR TITLE
fix: replace tbl_flatten to flatten():totable()

### LINKED ISSUE #408: Deprecation warnings on neovim 0.11
Running neovim 0.11 will raise deprecation warnings for a lot of APIs.

For example

Screenshot 2024-05-18 at 11 23 02

### PR DESCRIPTION
**Pull request by pablobfonseca**
This also fixes #408

### CODE REVIEW

**Comment by rcarriga** [comment]
Thanks for the PR!

**Comment by codymikol** [comment]
This introduced a regression for me,

````
neotest-kotest: ...local/share/nvim/lazy/neotest/lua/neotest/utils/init.lua:4: E5560: vimL function must not be called in a lua loop callback
stack traceback:
	...ocal/share/nvim/lazy/neotest/lua/neotest/client/init.lua:89: in function <...ocal/share/nvim/lazy/neotest/lua/neotest/client/init.lua:88>
	[C]: in function 'has'
	...local/share/nvim/lazy/neotest/lua/neotest/utils/init.lua:4: in function 'tbl_flatten'
	...al/share/nvim/lazy/neotest/lua/neotest/lib/file/init.lua:358: in function 'match_root_pattern'
	/home/cody/dev/src/neotest-kotest/lua/neotest-kotest.lua:13: in function 'root'
	/home/cody/dev/src/neotest-kotest/lua/neotest-kotest.lua:115: in function 'build_spec'
	...al/share/nvim/lazy/neotest/lua/neotest/client/runner.lua:76: in function '_run_tree'
	...al/share/nvim/lazy/neotest/lua/neotest/client/runner.lua:65: in function <...al/share/nvim/lazy/neotest/lua/neotest/client/runner.lua:22>
	[C]: in function 'xpcall'
````

I'll try and do some more digging

**Comment by rcarriga** [comment]
Should be fixed in latest commit :smile:

**Comment by codymikol** [comment]
thanks!

**Pull request merged**
